#!/bin/bash
sudo apt install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    software-properties-common 
curl -fsSL https://yum.dockerproject.org/gpg | sudo apt-key add - 
sudo add-apt-repository \
    "deb https://apt.dockerproject.org/repo/ \
    ubuntu-$(lsb_release -cs) \
    main" 
sudo apt update
sudo apt -y install docker.io
# add current user to docker group so there is no need to use sudo when running docker
sudo usermod -aG docker $(whoami)
