#!/bin/bash
apt -y update
apt -y install apache2
OS_VERSION=$(cat /proc/version)
echo "<html><body bgcolor=white><center><h1><p><font color=blue>Hello World <br> $OS_VERSION</h1></center></body></html>" > /var/www/html/index.html
sudo systemctl start apache2
chkconfig httpd on
